# Generated by Django 3.2.7 on 2021-10-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20211012_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created DateTime'),
        ),
        migrations.AlterField(
            model_name='post',
            name='like_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='like_count'),
        ),
    ]
